"""empty message

Revision ID: 66ad3e592cb4
Revises: 60d183293b66
Create Date: 2020-02-17 15:20:12.175979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ad3e592cb4'
down_revision = '60d183293b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###
